"""update status enum to company_member with canceled

Revision ID: 5aaa0ea81942
Revises: 898e00397b53
Create Date: 2025-11-21 11:11:00.072007

"""

from typing import Sequence, Union

from alembic_postgresql_enum import TableReference

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5aaa0ea81942"
down_revision: Union[str, None] = "898e00397b53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="status_enum",
        new_values=["pending", "accepted", "declined", "canceled"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="invitations", column_name="status"
            ),
            TableReference(
                table_schema="public", table_name="requests", column_name="status"
            ),
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="status_enum",
        new_values=["pending", "accepted", "declined"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="invitations", column_name="status"
            ),
            TableReference(
                table_schema="public", table_name="requests", column_name="status"
            ),
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
