"""create user table

Revision ID: 84eb4c449f00
Revises: 6f3e84bd0a92
Create Date: 2025-10-30 12:30:32.862552

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "84eb4c449f00"
down_revision: Union[str, None] = "6f3e84bd0a92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
