"""initial empty migration

Revision ID: 9e0e9cda1a36
Revises: 
Create Date: 2025-10-30 14:04:40.036931

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "9e0e9cda1a36"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
