"""use Role enum with enum autogeneration

Revision ID: ae139115ee90
Revises: b527a5bd836a
Create Date: 2025-11-16 23:24:22.762258

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae139115ee90"
down_revision: Union[str, None] = "b527a5bd836a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("owner", "admin", "member", name="role_enum").create(op.get_bind())
    op.alter_column(
        "company_members",
        "role",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum("owner", "admin", "member", name="role_enum"),
        existing_nullable=False,
        postgresql_using="role::role_enum",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "company_members",
        "role",
        existing_type=sa.Enum("owner", "admin", "member", name="role_enum"),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    sa.Enum("owner", "admin", "member", name="role_enum").drop(op.get_bind())
    # ### end Alembic commands ###
